[package]
name = "testing"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
elaborate = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snapbox = "0.6"
tempfile = "3.23"
toml = "0.9"

[lints]
workspace = true
